
#########################################################
#              DNS Details                              #
#########################################################
dns:
  hostname:
  certificateARN:

applications:
#########################################################
#     Values for DB server Containers                   #
#########################################################
  dbserver:
    replicas:
    image: 
      repository: 
      name: 
      tag: 
      pullPolicy:
    service:
      port: 8000
      scheme: http
      type: ClusterIP 

#########################################################
#     Values for springboot Containers                  #
#########################################################
  springboot:
    replicas:
    image: 
      repository: 
      name: 
      tag: 
      pullPolicy: 
    service:
      port: 8080
      scheme: http 
      type: ClusterIP

#########################################################
#     Values for nginx Containers                  #
#########################################################
  nginx:
    replicas:
    image: 
      repository: 
      name: 
      tag: 
      pullPolicy: 
    service:
      port: 80
      scheme: http 
      type: NodePort

#########################################################
#     Values for nodejs Containers                  #
#########################################################
  nodejs:
    replicas:
    image: 
      repository: 
      name: 
      tag: 
      pullPolicy: 
    service:
      port: 4000
      scheme: http 
      type: ClusterIP

#########################################################
#     Values for python Containers                  #
#########################################################
  python:
    replicas:
    image: 
      repository: 
      name: 
      tag: 
      pullPolicy: 
    service:
      port: 5000
      scheme: http
      type: ClusterIP 